### PR TITLE
Issues/8

### PR DESCRIPTION
**Pull request by Shivin89**
@kirksl 

- Added a new parameter to "sendlog" method to saveFile  (RP report portal class)
- Added line of code to get the images from the steps in the feature end method and used the above parameter to save the image to RP.

### CODE REVIEW

**Comment by kirksl** [comment]
@Shivin89 thanks!  I just tested this and it seems to be working.  Is it possible to update this to attach all screenshots taken within the scenario?  It only seems to be attaching the last image before a failure occurs.

For example if I do the following:
```
Scenario: ui 1
    * configure driver = { type: 'chrome' }
    * driver 'https://github.com/login'
    * screenshot()
    * screenshot()
    * screenshot()
    * assert 1 == 0
```
 
Only the last screenshot is attached.

Also curious would it be possible to update RPReporter to save files at the launch level?
I've wanted to be able to attach things like `karate-timeline.html` within the ./target/karate-reports directory

**Comment by Shivin89** [comment]
Hi @kirksl 

for me it works for all the screenshots taken in a scenario and it attaches to the test level , I’m not sure why with this example it’s only attaching last screenshot as you can see in the code I’m fetching image from each step and then attaching.

I think there is a way to attach at Launch level as well as per the RP docs. , but didn’t tried that

**Comment by kirksl** [comment]
@Shivin89 thanks for confirming I can see you are looping through all test steps too.  I would be curious if you can get all images to attach using this karate-maven-gradle project.  If you can it would be great if you could add a test showing it work.  I tried using this project and the test shown in my last post.

**Comment by kirksl** [comment]
@Shivin89 I've debugged why all images were not attaching.  I noticed that when a step did not have a "doc_string" the logic to attach images is bypassed.  I've fixed this.  Before image attached shows the issue before the fix, After image shows the issue resolved.  Let me know if you agree.  I'll also look into adding attachments at the launch level when I get more time.
before
after

**Comment by Shivin89** [comment]
@kirksl  Thanks for debugging and yes I think you are right I saw all my screenshot steps and all were having docstring that's why they got attached.

**Pull request merged**
